version: "3.9"

services:
  backend:
    image: ghcr.io/schoolofelvish/skillbridge_backend:latest
    restart: always
    env_file:
      - ./backend/.env
    labels:
      - traefik.enable=true
      - traefik.http.services.backend.loadbalancer.server.port=3000
      - traefik.http.routers.backend.rule=Host(`skillbridge.me`) && PathPrefix(`/api`)
      - traefik.http.routers.backend.entrypoints=websecure
      - traefik.http.routers.backend.tls.certresolver=le


  frontend:
    image: ghcr.io/schoolofelvish/skillbridge_frontend:latest
    restart: always
    env_file:
      - ./frontend/.env
    labels:
      - traefik.enable=true
      - traefik.http.services.frontend.loadbalancer.server.port=3001
      - traefik.http.routers.frontend.rule=Host(`skillbridge.me`)
      - traefik.http.routers.frontend.entrypoints=websecure
      - traefik.http.routers.frontend.tls.certresolver=le

  traefik:
    image: traefik:v2.10
    restart: always
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.le.acme.tlschallenge=true"
      - "--certificatesresolvers.le.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.le.acme.email=work.pupko@gmail.com"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock:ro
    labels:
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.permanent=true"
      - "traefik.http.routers.redirs.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.redirs.entrypoints=web"
      - "traefik.http.routers.redirs.middlewares=redirect-to-https"

  db:
    image: postgres:14
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: password
    logging:
      driver: none

volumes:
  db_data:
